title: STARRY-S' Blog
subtitle: Morning.
description: 如果接受一切，就不会受伤
author: STARRY-S
email: hxstarrys@gmail.com
language: zh-Hans

# Those makes up your site's full URL.
baseURL: https://blog.starry-s.moe
rootDir: /

# Those paths exists on your disk.
srcDir: srcs
docDir: docs
themeDir: themes/aria

# Those paths are under `docDir`.
indexDir: .
archiveDir: archives
categoryDir: categories
tagDir: tags

# Those paths are under `srcDir`.
skipRender:
  - README.md
  - CNAME
  - BingSiteAuth.xml

perPage:
  index: 10
  archives: 15
  category: 15
  tag: 15

nunjucks:
  autoescape: false

marked:
  gfm: true

stylus:
  compress: false
  sourcemaps:
    comment: true
    inline: true
    sourceRoot: ''
    basePath: .

highlight:
  enable: false
  gutter: false
  hljs: true

search:
  enable: true
  path:
    - search/1.json
    - search/2.json
    - search/3.json
  page: search/index.html

aplayer:
  enable: true
  cdn:
    # style: "https://cdnjs.cloudflare.com/ajax/libs/aplayer/1.10.1/APlayer.min.css"
    # script: "https://cdnjs.cloudflare.com/ajax/libs/aplayer/1.10.1/APlayer.min.js"
    style: "/css/APlayer.min.css"
    script: "/js/APlayer.min.js"

feed:
  enable: true
  path: atom.xml
  limit: 20
  hub:
  content: true
  contentLimit: 140

sitemap:
  enable: true
  path: sitemap.xml
